import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "fallen solider · Ady Mehta",
  description: "Today I'm a fallen soldier.",
};

const postContent = `Today I'm a fallen soldier. It's 9:14 at night. I've probably been on my laptop for 10-12 hours continuous. The last week or so has been really hard to catch a break on anything, and today I'm making this post as a last-resort copium post. 
Normally I wouldn't just brain-dump whatever I'm thinking about right now on a Google Doc and send it over to Inkhaven, but today I feel like I have zero brain cells left. My brain feels scrambled and I do have a sense of impending stress. 
Let me back up and give some context on all the things that are going on in my life right now, to lay out how things have been. So there's been Inkhaven, and the forcing function of writing a blog post every single day has certainly been a bit taxing, but I think it's actually helped me build a muscle for just getting shit done. I also feel that I can write faster now, and I'm grateful for three types of posts that have come out. 
The first ones have been healing posts where I really try to tune into myself and talk about the process of writing, how cathartic things are, how I'm feeling. A sub-range of this includes notes to my sister, a brief note, a letter to my mother, and I hope I'll have space to write a few more to some of my close family members and my kindergarten teacher. Overall these posts have been the most fulfilling posts so far.
The second type of post is a bit on the research exploration side, where I've dug into open-weight governance, export controls, read some AI political philosophy essays, and most recently got to write a little bit about power coordination and AI-enabled coups. So these overall I think have distilled down the research exploration into little tidbits that have been enriching for me, and they have served their purpose well. I now feel more confident in the fact that my horizons have expanded, and I look forward to continuing writing into these topics onwards of May.
Then the last type of posts have been these meta posts where I've tried to basically — well, I guess I haven't really tried, but I just laid some time out to describe my current personal situation and then do some career planning on paper that could help me out. Those have been good for gaining a bit of traction too to attract certain voices from people who can be of help, especially with career guidance or introductions to certain people who are hiring right now.
And then a small fourth type of post has been these low-effort posts that I put out really when I do want to embody the spirit of still being an active Inkhaven participant. There's a part of me that doesn't want to let Ben down for all that he's invested into me. But some days I really just don't have the bandwidth.
So maybe now I can explain why I don't have the bandwidth. One is that I'm trying to juggle contract work alongside Inkhaven, and that's been a little bit challenging. I basically need to solidify as many income streams as I can. And that honestly took quite a bit of time today, it seemed. Typically I have to work on this stuff over the weekend, which is not the most fun, but it has to be done.
The second thing is that I am just trying to secure a second source of income for the summer anyway, one that is enriching and also progresses my career. I ended up accepting an offer with the Tarbell Fellowship which starts in September, and the summer will be the journalism writing course which I think will be really enriching. However, I also would like to explore the possibility of doing a fellowship or something on the side. And for these fellowships, it's just been hectic trying to get the applications in for them.
So I submitted an application to GovAI, the Summer DC Fellowship, a long time ago, and to really show my enthusiasm, I sent them four follow-up emails with around 12 research documents showing how I've continued keeping up pace with AI policy after the interview. And there's also the Generator application, which is due tomorrow. And I'm feeling good about the initial application. I'm almost done, just some finishing touches which hopefully will just take an hour. But I guess I have been trying to scope out additional projects to propose to them so that I basically am hedged somewhat against the risk of not being a strong enough applicant. I guess I just have this existential fear that I won't really have anything for the summer outside of the Tarbell Fellowship, which honestly I'd be pretty fine just doing. But I think it's just the prospect of doubling income, which is really important right now.
Then there's some upcoming fellowships like the Astra Fellowship that I need to work on over this week, as well as the Pivotal Fellowship just coming up. And for each one there's just a bunch of work that needs to be done, and I need to figure stuff out soon. So this next week is going to be super hectic getting those in.
Then just a few minutes ago, one of my friends was able to catch a grant maker at Coefficient Giving at this talk at Stanford and convinced him to come talk to Berkeley on Friday. So now we have to organize an entire event for that, and me and her are the only people doing the logistics. So that will be intense but fun, hopefully worth it. I'm really excited about grant making. Eventually, it seems like it's a very intellectually enriching, demanding career, but one that's also very high impact. And it seems like right now is a good time to learn how to become a grant maker. I guess need to put my all in for this.
So here's the landscape of things that are going on. Tomorrow I'm talking with this person about a Special Projects role at Forethought Institute. And I feel like I've just been this week reading their research strategy documents on AI-enabled coups, trying to understand how secretly loyal AIs can create this sort of — they can have these backdoors that can cause a coup to take place, and why the need for good AI character that can ideally encourage pro-social behavior and overall be robust enough is something that I've been trying to grapple with. But honestly, I feel like I've just been getting overwhelmed by all the content and I haven't even gotten time to say things out loud and reason through them. Which is the part that's concerning me for tomorrow morning — I feel like I just know the buzzwords now, but I haven't really — I just haven't had time to let them sit into my head and for me to draw internal associations between them. So I don't know how I'm feeling about that. 
I guess something I can probably try and do tomorrow is maybe just throw in the current notes I've taken into Claude and ask it to create some illustrations that can help me understand the arguments better. That could be good. But honestly, pretty low expectations for tomorrow. Yeah, I think. But I guess still, I at least got exposed to a new research field, and I hope I'll have time after the chat to continue looking into it for what it's worth.
Oh yeah. So on that note, will I even have time? The thing is, I feel like I'm so spread thin right now. I haven't even talked about the fact that yesterday I was looking into this new data center build-out project where local NIMBY groups are trying to basically pause data center build-outs together at the state level and in their local communities, and they're being successful. And I was wondering if we could do some sort of coordination among that. 
I also have to figure that one out this week, and I don't know, it's just looking kind of rough. Another thing is that I'm supposed to put out this blog post on a dividend fund and reach out to these different outlets to try and publish a short essay on the way that technology is historically diffused in the economy. And I've just been behind on that as well. Today I was talking to a student group leader about potentially running these AI policy summer workshops.
And I don't know, I feel like I'm just trying to take opportunities left and right out of defeat that I'm not doing enough, and the fear that I won't have anything meaningful to work on for the summer. And all this is just causing a lot of overwhelmingness and a lot of stress. I was really looking forward to having today's post be a very meaningful, thoughtful post. Ideally being a letter to my kindergarten teacher whose birthday, by the way, was a month ago and I still haven't written her a letter. So I actually broke the 15-year tradition of writing to her because I was just too overwhelmed and not able to keep track of things.
And I don't know, overall, sometimes today I'm just asking myself, is all this even worth it? I feel like I'm perpetually in this race to just grab onto something, and I don't even have time to think through anything myself. It's a really shitty, bad feeling of being overwhelmed. Kind of feel frozen from the inside, where sometimes I just stare into these research documents and nothing clicks to me at all. And to that end, I guess acknowledging it makes me feel good in the moment, but the problem is reoccurring. So the question is how to solve the problem in the first place.
I don't know. This post is probably going to be hidden from the public dashboard because in part, I guess I'm just ashamed that things have come to this level, where a sort of random rant has to count for today's post. Nothing more thoughtful of substance. But if anyone does end up reading this post, then honestly, I could really use some advice on how to just figure things out. How do I just pick one impactful project, find someone who's willing to support it, and then go from there and not have to worry about the rest? Yeah, I just feel like I'm being drawn way too thin right now. And I just hope that the last three days of Inkhaven posts are more meaningful for me than what I'm currently putting out.`;

export default function FallenSoliderPost() {
  return (
    <article className="py-6 sm:py-8">
      <p className="mb-4">
        <Link href="/writing" className="hyperlink text-base font-normal">
          ← Writing
        </Link>
      </p>

      <h1 className="text-2xl sm:text-3xl font-bold mb-6 sm:mb-8 leading-tight">
        fallen solider
      </h1>

      <div className="whitespace-pre-wrap text-[1.05rem] sm:text-[1.1rem] leading-relaxed">
        {postContent}
      </div>
    </article>
  );
}
